[platformio]
src_dir = firmware/z-duino
data_dir = build/data
extra_configs = secrets.ini

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld
lib_deps =
    bblanchon/ArduinoJson
    links2004/WebSockets
monitor_speed = 115200
upload_speed = 460800
